# Generated by Django 2.1.7 on 2019-03-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_00', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookshop',
            options={'verbose_name': 'Book Shop', 'verbose_name_plural': 'Book Shops'},
        ),
    ]
